DEFAULT_FORWARD_ADDRESS = "http://176.63.245.216:1235/"
CLASSIFICATION_FORWARD_ADDRESS = ""
FORWARD_ADDRESS = None

DEFAULT_WEBSITE_ROOT = "Website is not available yet, please try again later"
WEBSITE_ROOT = None